### ISSUE TITLE
1.21 issue

### ISSUE THREAD

**Issue by mulissi** [DerFrZocker/Ore-Control#34]
[00:00:22] [Server thread/INFO]: [ore-control] Enabling ore-control v2024.06.16
[00:00:22] [Server thread/ERROR]: Error occurred while enabling ore-control v2024.06.16 (Is it up to date?)
java.lang.IllegalStateException: No NMSReplacer found for version '1.21.1', this is a bug!
	at ore-control-2024.06.16.jar/de.derfrzocker.ore.control.OreControl.getNmsReplacer(OreControl.java:195) ~[ore-control-2024.06.16.jar:?]
	at ore-control-2024.06.16.jar/de.derfrzocker.ore.control.OreControl.onEnable(OreControl.java:144) ~[ore-control-2024.06.16.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-10-098bd39]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-10-098bd39]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-10-098bd39]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-10-098bd39]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:293) ~[paper-1.21.1.jar:1.21.1-10-098bd39]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-10-098bd39]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-10-098bd39]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:00:22] [Server thread/INFO]: [ore-control] Disabling ore-control v2024.06.16

This happened when I launched my server after updating to 1.21. I'm using Paper.

**Comment by mulissi** [comment]
Update: I'm using 1.21.1

Server is still Paper

**Comment by DerFrZocker** [comment]
Fixed in [v2024.09.10](https://github.com/DerFrZocker/Ore-Control/releases/tag/v2024.09.10)
